version: "3"
services:
  react-app:
    build: ./
    ports:
      - "8080:80"
    volumes:
      - /usr/app/node_modules

  test:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    command: ["npm", "run", "test"]