version: "3"
services:
  react-app:
    build:                            # ./ cannot be used here because the dockerfile has a .dev at the end. Instead...
      context: ./                     # specify location of the dockerfile
      dockerfile: Dockerfile.dev      # Specify new customerised dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app

  test:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    command: ["npm", "run", "test"]